### ISSUE TITLE
uninitialized constant Fluent::Plugin::SyslogInput::PRIORITY_MAP

### ISSUE THREAD

**Issue by i5okie** [ApplauseOSS/fluent-plugin-heroku-http#6]
Getting this error after plugin is installed. Fluentd crashloops after.
```[error]: unexpected error error_class=NameError error="uninitialized constant Fluent::Plugin::SyslogInput::PRIORITY_MAP"```

**Comment by jnarowski** [comment]
Me too

**Comment by jnarowski** [comment]
If this maintainer isn't responsive, @i5okie any interest in forking this and making our own updated plugin?

**Comment by austenmadden** [comment]
https://github.com/ApplauseOSS/fluent-plugin-heroku-http/pull/7

**Comment by B0go** [comment]
@austenmadden thanks for this PR, I am also interested in this fix and willing to contribute to keep this project alive if needed

(cc @jnarowski)

**Comment by wolf31o2** [comment]
Sorry about the slow response. This got lost in the ~30K GitHub emails I get a day. 😁

**Comment by wolf31o2** [comment]
I just pushed v0.0.2 to RubyGems
```
$ rake release[origin]
fluent-plugin-heroku-http 0.0.2 built to pkg/fluent-plugin-heroku-http-0.0.2.gem.
Tagged v0.0.2.
Pushed git commits and tags.
Pushing gem to https://rubygems.org...
Successfully registered gem: fluent-plugin-heroku-http (0.0.2)
Pushed fluent-plugin-heroku-http 0.0.2 to rubygems.org
```
